language: node_js
env:
  - SUPERTAPE_NO_PROGRESS_BAR=1
node_js:
  - 15
  - 14
script:
  - npm run bootstrap
  - npm run lint
  - npm run coverage:long
  - npm run report
notifications:
  email:
    on_success: never
    on_failure: change
sudo: false
cache: false
